version: '3.8'
services:
  training:
    build:
      context: ./app  # Point to the FastAPI project directory
      dockerfile: Dockerfile
    volumes:
      - ./app:/app  # Mount the FastAPI project directory
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - WATCHFILES_FORCE_POLLING=true 
