FROM python:3.12-slim
WORKDIR /app

# Copy just the requirements file first to leverage Docker cache
COPY requirements.txt /app/
RUN pip install --no-cache-dir --upgrade -r requirements.txt


EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
